# LamPy

## Short-term Goal 

1. Wrapper: A wrapper of `numpy`
2. Scheduling: Take over the scheduling of calculation in the cloud

## Development

### Version 1: Support very simple calculation.

In [145]:
import numpy as np

In [207]:
class LamObject():
    def __init__(self, val=None):
        if isinstance(val, numpy.ndarray):
            self.val = val
        else:
            self.val = np.array(val)
        
    def __add__(self, obj):
        print(f"Doing {self.val} + {obj.val}")
        return LamObject(self.val + obj.val)
    
    def __str__(self):
        return self.val.__str__()

    def __repr__(self):
        return self.val.__str__()

In [208]:
a = LamObject([1,2,3])
b = LamObject([1,2,3])
c = a + b

Doing [1 2 3] + [1 2 3]


In [209]:
c

[2 4 6]

### Version 2: Create a graph diagraph of the Lampy object

In [326]:
class LamObject():
    def __init__(self, val=None, children=[]):
        self.children = children   # [LamObject]
        if isinstance(val, numpy.ndarray):
            self.val = val
        else:
            self.val = np.array(val)
        
    def run(self, cache=False):
        print("Run")
        if cache and self.val is: 
            return self.val
        if not len(self.children):
            return self.val
        for i in self.children:
            i.run()
        sum = self.children[0].val
        for i in self.children[1:]:
            sum += i.val
        self.val = sum
        return sum
        
        
    def __add__(self, obj):
        return LamObject(val=None, children=[self, obj])
    
    def __str__(self):
        return self.val.__str__()

    def __repr__(self):
        return self.val.__str__()

In [327]:
a = LamObject([1,2,3])
b = LamObject([1,2,3])
c = a + b

In [328]:
c

None

In [329]:
c.run()

Run
Run
Run


array([2, 4, 6])

In [330]:
c

[2 4 6]

In [332]:
c.run(cache=True)

Run


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()